# Generated by Django 5.1.4 on 2025-05-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plain_password',
        ),
    ]
