# Generated by Django 5.1.4 on 2025-05-24 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('parents_name', models.CharField(max_length=200)),
                ('professional_status', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=20)),
                ('fav_colour', models.CharField(max_length=100)),
                ('fav_food', models.CharField(max_length=100)),
                ('fav_fruit', models.CharField(max_length=100)),
                ('fav_singer', models.CharField(max_length=100)),
                ('fav_actor', models.CharField(max_length=100)),
                ('fav_actress', models.CharField(max_length=100)),
                ('fav_movie', models.CharField(max_length=100)),
                ('fav_timepass', models.CharField(max_length=200)),
                ('fav_destination', models.CharField(max_length=200)),
                ('school_photo', models.ImageField(blank=True, null=True, upload_to='school_photos/')),
                ('college_photo', models.ImageField(blank=True, null=True, upload_to='college_photos/')),
                ('memory_photo', models.ImageField(blank=True, null=True, upload_to='memory_photos/')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
