# Generated by Django 5.1.4 on 2025-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='memory_photo',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_desc_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_desc_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_desc_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_desc_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_desc_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='memory_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='memory_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='memory_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='memory_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='memory_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='memory_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
