# Generated by Django 5.1.4 on 2025-05-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_patientdetails_memory_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDetails',
        ),
    ]
