# Generated by Django 5.1.4 on 2025-05-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_patientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('current_address', models.TextField()),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('school_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('favourite_destination', models.CharField(max_length=100)),
                ('favourite_food', models.CharField(max_length=100)),
                ('favourite_fruit', models.CharField(max_length=100)),
                ('favourite_colour', models.CharField(max_length=100)),
                ('favourite_movie', models.CharField(max_length=100)),
                ('favourite_actor', models.CharField(max_length=100)),
                ('favourite_actress', models.CharField(max_length=100)),
                ('favourite_singer', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='patient_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='patient_photos/')),
                ('category', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('memory', 'Memory')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientdetails')),
            ],
        ),
    ]
