# Generated by Django 5.1.4 on 2025-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patientdetails_patientphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_actor',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_actress',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_colour',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_destination',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_food',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_fruit',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_movie',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='favourite_singer',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='school_name',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PatientPhoto',
        ),
    ]
