# Generated by Django 5.1.4 on 2025-05-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_patientdetails_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='photo',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientdetails')),
            ],
        ),
    ]
