# Generated by Django 5.1.4 on 2025-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_patientdetails_photo_patientdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
