# Generated by Django 5.1.4 on 2025-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patientdetails_birthplace_patientdetails_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
