# Generated by Django 5.1.4 on 2025-05-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_collegephoto_memoryphoto_schoolphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryphoto',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='schoolphoto',
            name='patient',
        ),
        migrations.DeleteModel(
            name='CollegePhoto',
        ),
        migrations.DeleteModel(
            name='MemoryPhoto',
        ),
        migrations.DeleteModel(
            name='SchoolPhoto',
        ),
    ]
