# Generated by Django 5.1.4 on 2025-05-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('other', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to='faces/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
