# Generated by Django 5.1.4 on 2025-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_collegephoto_memoryphoto_schoolphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLifeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Bathing 🚿', 'Bathing 🚿'), ('Sleeping 💤', 'Sleeping 💤'), ('Drinking Water 💧', 'Drinking Water 💧'), ('Breakfast 🍳', 'Breakfast 🍳'), ('Lunch 🍛', 'Lunch 🍛'), ('Dinner 🍽️', 'Dinner 🍽️'), ('Skincare 💆', 'Skincare 💆'), ('Watering Plants 🌿', 'Watering Plants 🌿'), ('Reading Books 📚', 'Reading Books 📚'), ('Arranging Room 🧹', 'Arranging Room 🧹')], max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
