# Generated by Django 5.1.4 on 2025-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dailylifereminder_medicalreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylifereminder',
            name='time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='medicalreminder',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
